### ISSUE TITLE
AniRena should not be added as "public" tracker - AniRena不應添加為“公共”跟踪器

### ISSUE THREAD

**Issue by Power2All** [DeSireFire/animeTrackerList#7]
Hi,

I am the founder and owner of AniRena.com and noticed you added the AniRena tracker to your listing.
This will not work, unless the torrent has been uploaded directly to AniRena, it's a "partial" public tracker, it allows you to upload anonymously a torrent, but the torrent will only get active on the tracker when it's uploaded at all.

Hope this is informative enough.

Kind regards.

======

你好

我是AniRena.com的創始人和所有者，並註意到您將AniRena跟踪器添加到了您的列表中。
這是行不通的，除非將種子直接上傳到AniRena，這是一個“部分”公共跟踪程序，它允許您匿名上傳一個種子，但是當種子完全上傳後，該種子將僅在跟踪器上處於活動狀態。

希望這能提供足夠的信息。

親切的問候。

**Comment by DeSireFire** [comment]
您好，

首先，感谢您的issue。AniRena.com 项目看起来棒极了 and you inspire me。
animeTackerList是从readme中公示的BT网站采集整理收录的。
这说明它们中某些magnet包含了AniRena的tracker和它们已经把torrent上传到了AniRena.com。
根据我的推断，可能是源自nyaa.si上的magnet使用了AniRena的trackers造成的。
animeTackerList没有办法做到torrent上传，
它更多是采集tracker的URL地址，并测试它们的链接是否通畅和速度是否足够快，
它没有办法对单一特定的torrent进行测试，工作量将会非常巨大。
AniRena tracker很优秀，所以自动添加到了animeTackerList。
animeTackerList是作为tracker推广，帮助BT爱好者提供更多尝试的机会。
我将会考虑在其他项目提供自动化上传torrent的功能。

然后，AniRena有不用上传torrent文件直接增加magnet的支持吗？如果有，希望告知我使用方法。

最后，我可以对AniRena进行采集用于animeTackerList吗？我会把它添加到readme当中。
如果您不希望animeTackerList将AniRena tracker添加到列表中，可以对我反馈。

期待您的答复。

親切的問候。
RaXianch

======

Hi,

First of all, thank you for your issue. The AniRena.com project looks great and you inspire me.
animeTackerList is collected and collected from the BT website published in the readme.
This means that some of them include AniRena tracker and they have uploaded the torrent to AniRena.com.
According to my inference, it may be caused by the magnet on nyaa.si using AniRena trackers.
animeTackerList has no way to do torrent upload,
It is more about collecting tracker URL addresses and testing whether their links are smooth and fast enough.
It has no way to test a single specific torrent, the workload will be huge.
AniRena tracker is excellent, so it is automatically added to my listing.
animeTackerList is promoted as a tracker to help BT enthusiasts provide more opportunities to try.
I will consider providing automatic uploading of torrents in other projects.

Then, does AniRena add magnet support directly without uploading torrent files? If so, I hope to inform me how to use it.

Finally, can I collect AniRena for animeTackerList? I will add it to the readme.
If you don't want animeTackerList to add AniRena tracker to the listing, you can give me feedback.

Looking forward to your reply.

Kind regards.

RaXianch

**Comment by Power2All** [comment]
Hi,

Sorry for the late response, been busy and forgot this was still open.
AniRena is being reworked on, and will introduce later a API that can be accessed to read out statistics.
AniRena is a partly closed tracker, but anonymous people can upload torrents.
Only torrents uploaded to AniRena, will be working on the back-end tracker, but any torrent that is not registered there, will not be accepted through the back-end tracker software.

> Then, does AniRena add magnet support directly without uploading torrent files? If so, I hope to inform me how to use it.

Magnet links are generated based on the torrent that is uploaded. Torrents got the SHA1 hashes needed in order to do anything at all. If a torrent is not uploaded to AniRena, it's not registered, and will not be handled by the back-end tracker.

> Finally, can I collect AniRena for animeTackerList? I will add it to the readme.

You can collect torrents from AniRena, no problem, it's made for that. New site will even make it easier for third party applications to communicate with AniRena.

I am also hosting a pure public back-end tracker, called gbitt.info which is a side project next to AniRena, which does accept any torrent.

Hope this is informative enough.

Kind regards.
Power2All

**Comment by DeSireFire** [comment]
oops..
Sorry,I thought that Information sent by the robot..
Therefore, I closed the issue.
Got it,
Thank you for everything.
Goo~lucky,buddy

**Comment by Power2All** [comment]
No problem, have a nice day :)
